### ISSUE TITLE
Calculating duration

### ISSUE THREAD

**Issue by JamesBremner** [JamesBremner/so76550312#3]
Notice this code

https://github.com/JamesBremner/so76550312/blob/8f3e0d8a1b69e1157e79403f2dd9f5db140b447b/src/profiles.cpp#L113-L119

What is the intention here?

1 `current_duration` is not used anywhere.  The code can be removed without any effect.

2 Why the reverse iterator?  The result would be identical if the forward iterator where used.

**Comment by ghost** [comment]
You are right. This is not needed anymore.
